### ISSUE TITLE
Connector doesn't crash/exit when mongodb authentication fails

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-MongoDB-Sink-Connector#2]
Connector instance keeps running even If the authentication of mongodb fails. Then keeps reporting `0 records have been processed`. 
The connector should exit the process with proper error code, to inform the status of the connector instance properly. 
```
[18:12:04] Nivethika Mahasivam: radar-mongodb-connector_1  | 	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
radar-mongodb-connector_1  | 	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:90)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:85)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:55)
radar-mongodb-connector_1  | 	at com.mongodb.Mongo.execute(Mongo.java:818)
radar-mongodb-connector_1  | 	at com.mongodb.Mongo$2.execute(Mongo.java:805)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:130)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:124)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:114)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoWrapper.checkConnection(MongoWrapper.java:106)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbWriter.<init>(MongoDbWriter.java:83)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:98)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:87)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,471] INFO MongoDB connection is has been closed (org.radarcns.mongodb.MongoWrapper)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,471] ERROR Task radar-connector-mongodb-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | org.apache.kafka.connect.errors.ConnectException: Cannot connect to MongoDB database
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbWriter.<init>(MongoDbWriter.java:85)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:98)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:87)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,473] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,473] ERROR Task radar-connector-mongodb-sink-0 threw an uncaught and unrecoverable exception during shutdown (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | java.lang.NullPointerException
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.stop(MongoDbSinkTask.java:145)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:127)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:121)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nivemaham** [comment]
A mongodb-connector issue. Reported [12](https://github.com/RADAR-CNS/MongoDb-Sink-Connector/issues/12)
